FROM toposoid/scala-knp:2.12.12-4.19

WORKDIR /app
ARG TARGET_BRANCH

ENV DEPLOYMENT=local

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/scala-common.git \
&& cd scala-common \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-common.git \
&& cd toposoid-common \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-knowledgebase-model.git \
&& cd toposoid-knowledgebase-model \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/scala-juman-knp.git \
&& cd scala-juman-knp \
&& git checkout scala-2.12-support \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-sentence-parser-japanese.git \
&& cd toposoid-sentence-parser-japanese \
#&& git checkout -b ${TARGET_BRANCH} origin/${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
