FROM toposoid/toposoid-scala-lib-base:0.7-SNAPSHOT

FROM toposoid/scala-knp:3.3.6-5.0
WORKDIR /root
COPY --from=0 /root/.ivy2/local ./.ivy2/local

WORKDIR /app
ARG TARGET_BRANCH
ENV DEPLOYMENT=local
ENV _JAVA_OPTIONS="-Xms2g -Xmx4g"

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/scala-juman-knp.git \
&& cd scala-juman-knp \
&& git checkout scala-3.3.6-knp-5.0-support \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-sentence-parser-japanese.git \
&& cd toposoid-sentence-parser-japanese \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH}
